server:
  port: 8080


spring:
  application:
    name: auth-service
    config:
      import: http://localhost:8081/
  freemarker:
    expose-request-attributes: true
  flyway:
    check-location: false
    baseline-on-migrate: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bestuser

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: true
        dialect: org.hibernate.dialect.PostgreSQLDialect