server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: person-service

  freemarker:
    expose-request-attributes: true
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${PERSON_SERVICE_DATABASE_URL:jdbc:postgresql://localhost:5432/person_service}
    username: postgres
    password: ${PERSON_SERVICE_DATABASE_PASSWORD}

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}